[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[dev]
  command = "vite --port 5175 --strictPort"
  targetPort = 5175
  port = 5176


